all:
  hosts:
    127.0.0.1:
      ansible_port: "{{ lookup('env','VAGRANT_PORT') }}"
  vars:
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become: true
    ansible_ssh_private_key_file: "{{ lookup('env','VAGRANT_PRIVATE_KEY') }}"

    zookeeper_service_environment_overrides:
      KAFKA_HEAP_OPTS: "-Xms64m -Xmx64m"

    kafka_broker_service_environment_overrides:
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
    kafka_broker:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        confluent.metrics.reporter.topic.replicas: 1

    kafka_connect_service_environment_overrides:
      KAFKA_HEAP_OPTS: "-Xms64m -Xmx64m"
    kafka_connect:
      properties:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1

    kafka_rest_service_environment_overrides:
      KAFKAREST_HEAP_OPTS: "-Xms64m -Xmx64m"

    ksql_service_environment_overrides:
      KSQL_HEAP_OPTS: "-Xms64m -Xmx64m"
    ksql:
      properties:
        ksql.internal.topic.replicas: 1
        ksql.streams.replication.factor: 1

    schema_registry_service_environment_overrides:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xms64m -Xmx64m"

zookeeper:
  hosts:
    127.0.0.1:
      zookeeper_id: 1
kafka_broker:
  hosts:
    127.0.0.1:
      broker_id: 1
schema_registry:
  hosts:
    127.0.0.1:
kafka_connect:
  hosts:
    127.0.0.1:
kafka_rest:
  hosts:
    127.0.0.1:
ksql:
  hosts:
    127.0.0.1:
control_center:
